version: '3.8'

services:
  api:
    build: .
    container_name: nest_prisma_jwt_api_prod
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    command: npm run start:prod

  db:
    image: postgres:14
    container_name: postgres_prod
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres_data_prod:
